version: '3'
services:
  api:
    build:
      context: .
      dockerfile: './Dockerfile_ui'
    ports:
    - "4200:4200"
    networks:
      - rans
networks:
  rans:  # Define the custom network name (must match the name in project 1)
    external: true  # Indicate that this network is external

